
version: '3.4'
networks:
  web:
    external:
      name: web
services:
  under_construction:
    image: luiscelano/under_construction:1.0
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.under_construction.entrypoints=http"
      - "traefik.http.routers.under_construction.rule=Host(`shop.lulisgt.com`)"
      - "traefik.http.middlewares.under_construction-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.under_construction.middlewares=under_construction-https-redirect"
      - "traefik.http.routers.under_construction-secure.entrypoints=https"
      - "traefik.http.routers.under_construction-secure.rule=Host(`shop.lulisgt.com`)"
      - "traefik.http.routers.under_construction-secure.tls=true"
      - "traefik.http.routers.under_construction-secure.service=under_construction"
      - "traefik.http.services.under_construction.loadbalancer.server.port=4000"
      - "traefik.docker.network=web"
      - "traefik.http.routers.under_construction-secure.tls.certresolver=le"
      - "traefik.http.routers.under_construction-secure.tls.domains[0].main=lulisgt.com"
      - "traefik.http.routers.under_construction-secure.tls.domains[0].sans=*.lulisgt.com"
    networks:
        web:
    ports:
      - 4000:4000